# Site settings
title: JKU Visual Data Science Lab
email: contact@jku-vds-lab.at
description: "JKU Visual Data Science Lab."
baseurl: ""
url: "https://jku-vds-lab.at"
twitter_username: marc_streit
github_username:  jku-vds-lab
youtube_username: UCH0ztMDNtQuIx0-ZWIavG0Q
# facebook_page: Caleydo/110550618994500
license_url: https://raw.githubusercontent.com/jku-vds-lab/jku-vds-lab.github.io/master/LICENSE
safe: false
lsi: false
google_analytics: "G-XB7C1C7YVE"
use_analytics: true

paper_content_url: http://data.jku-vds-lab.at/papers/
poster_content_url: http://data.jku-vds-lab.at/posters/
data_url: http://data.jku-vds-lab.at/

# Build settings

permalink: pretty
sass:
  sass_dir: _sass
# exclude from build
exclude: ["README.md", "Rakefile", "changelog.md", ".idea/", "Gemfile", "Gemfile.lock", "rvm.env"]

# code highlighter
#highlighter: rouge

# Collections
collections:
  tools:
    output: true
    permalink: /tools/:path/
  themes:
    output: true
    permalink: /:path/
  persons:
    output: true
    permalink: /persons/:path/
  alumni:
    output: true
    permalink: /alumni/:path/
  publications:
    output: true
    permalink: /publications/:path/
  edits_comments_books:
    output: true
    permalink: /edits_comments_books/:path/
  # thesis:
  #   output: true
  #   permalink: /thesis/:path/
  releases:
    output: true
    permalink: /releases/:path/
  videos:
    output: false
    permalink: /videos/:path/
  datasets:
    output: false
    permalink: /datasets/:path/
  institutions:
    output: false
    permalink: /institutions/:path/
  collaborators:
    output: false
    permalink: /collaborators/:path/
  funding:
    output: false
    permalink: /funding/:path/
